<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Umpan extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        //is_login();
        $this->load->model('Umpan_model');
        $this->load->library('form_validation');
    }

    public function index()
    {
        $q = urldecode($this->input->get('q', TRUE));
        $start = intval($this->uri->segment(3));
        
        if ($q <> '') {
            $config['base_url'] = base_url() . '.php/c_url/index.html?q=' . urlencode($q);
            $config['first_url'] = base_url() . 'index.php/umpan/index.html?q=' . urlencode($q);
        } else {
            $config['base_url'] = base_url() . 'index.php/umpan/index/';
            $config['first_url'] = base_url() . 'index.php/umpan/index/';
        }

        $config['per_page'] = 10;
        $config['page_query_string'] = FALSE;
        $config['total_rows'] = $this->Umpan_model->total_rows($q);
        $umpan = $this->Umpan_model->get_limit_data($config['per_page'], $start, $q);
        $config['full_tag_open'] = '<ul class="pagination pagination-sm no-margin pull-right">';
        $config['full_tag_close'] = '</ul>';
        $this->load->library('pagination');
        $this->pagination->initialize($config);

        $data = array(
            'umpan_data' => $umpan,
            'q' => $q,
            'pagination' => $this->pagination->create_links(),
            'total_rows' => $config['total_rows'],
            'start' => $start,
        );
        $this->template->load('template','umpan/tbl_umpan_list', $data);
    }

    public function read($id) 
    {
        $row = $this->Umpan_model->get_by_id($id);
        if ($row) {
            $data = array(
		'no' => $row->no,
	    );
            $this->template->load('template','umpan/tbl_umpan_read', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('umpan'));
        }
    }

    public function create() 
    {
        $data = array(
            'button' => 'Create',
            'action' => site_url('umpan/create_action'),
	    'no' => set_value('no'),
	);
        $this->template->load('template','umpan/tbl_umpan_form', $data);
    }
    
    public function create_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->create();
        } else {
            $data = array(
	    );

            $this->Umpan_model->insert($data);
            $this->session->set_flashdata('message', 'Create Record Success 2');
            redirect(site_url('umpan'));
        }
    }
    
    public function update($id) 
    {
        $row = $this->Umpan_model->get_by_id($id);

        if ($row) {
            $data = array(
                'button' => 'Update',
                'action' => site_url('umpan/update_action'),
		'no' => set_value('no', $row->no),
	    );
            $this->template->load('template','umpan/tbl_umpan_form', $data);
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('umpan'));
        }
    }
    
    public function update_action() 
    {
        $this->_rules();

        if ($this->form_validation->run() == FALSE) {
            $this->update($this->input->post('no', TRUE));
        } else {
            $data = array(
	    );

            $this->Umpan_model->update($this->input->post('no', TRUE), $data);
            $this->session->set_flashdata('message', 'Update Record Success');
            redirect(site_url('umpan'));
        }
    }
    
    public function delete($id) 
    {
        $row = $this->Umpan_model->get_by_id($id);

        if ($row) {
            $this->Umpan_model->delete($id);
            $this->session->set_flashdata('message', 'Delete Record Success');
            redirect(site_url('umpan'));
        } else {
            $this->session->set_flashdata('message', 'Record Not Found');
            redirect(site_url('umpan'));
        }
    }

    public function _rules() 
    {

	$this->form_validation->set_rules('no', 'no', 'trim');
	$this->form_validation->set_error_delimiters('<span class="text-danger">', '</span>');
    }

}

/* End of file Umpan.php */
/* Location: ./application/controllers/Umpan.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2024-08-01 21:06:47 */
/* http://harviacode.com */